# fly.toml app configuration file generated for uba-staging-app on 2026-05-29T03:47:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uba-staging-app'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile.fly'

[deploy]
  strategy = 'rolling'

[env]
  NGINX_BACKEND_URL = 'https://uba-staging-api.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'get'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
